# Generated by Django 3.0.8 on 2020-08-10 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('temas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataFesta', models.DateField()),
                ('horarioInicio', models.TimeField()),
                ('horarioTermino', models.TimeField()),
                ('valorCobrado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('endereco', models.CharField(max_length=255)),
                ('complemento', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temas.Tema')),
            ],
        ),
    ]
